# Site
repository: safoorsafdar/safoorsafdar.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Safoor Safdar
title: Cloud Solution Architect / Consultant DevOps
description: "Hi there! I help businesses to adapt and improve DevOps. I love building and optimizing infrastructure, and applications. I like to automate dull tasks, and implement observability. #docker #kubernetes #aws #azure #prometheus"
email: talk@safoorsafdar.com
website:

author:
  name: Safoor Safdar
  url: https://safoorsafdar.com/
  twitter: safoorsafdar
# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: safoorsafdar
github_username: safoorsafdar
# stackoverflow_username: "1728836"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: safoorsafdar
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Schedule a Google Meet
    icon: far fa-calendar-plus
    url: https://calendly.com/safoor-safdar/get-to-know
  - title: Blog
    icon: fas fa-blog
    url: https://blog.safoorsafdar.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-4S133Q4XWS"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Cloud Solution Architect / Consultant DevOps with over 11+ years of experience in a fast-paced environment.

  - Working experience on AWS and on-premises, architect highly available, scalable, and fault-tolerant architectural solutions for clients to help them migrate successfully from current infrastructure (on-premise) to AWS cloud or set up from scratch on AWS.
  - Highly motivated and committed Consultant DevOps experienced in Automating, Configuring, and deploying instances on AWS and on-premises.
  - Strong knowledge and skills in AWS Architecture Design, especially in Production, Development, and Testing environments.
  - 5+ years of application development experience using PHP and JS.
  - 6+ years of Consultant DevOps with AWS, GCP, and Azure, on-premise.
  - Solid experience in all the phases of the Software development life cycle starting from requirement gathering, analysis, design, coding, implementation, and support.
  - AWS Certified Cloud Practitioner, Ubuntu, RHEL, Centos and AWZ2, AWS, Azure and GCP cloud services, TeamCity, Gitlab, and DeployBot, Kubernetes using Kubeadm and Kubespray, Docker, Helm, Shell Script, Prometheus, Grafana, containerization.
  - Proficient experience in Infrastructure as code using Terraform, Ansible, and Cloud ops automation using Python for AWS. Monitoring and Observability implementation for AWS, Azure, and on-prem infrastructure/containers orchestration.

  Proficient with PHP, JavaScript/NodeJS, Python. Have experience in Laravel, Zend, Magento2, MEAN and angular, beginner of ReactJS, and desktop application development using Electron. I have experience in large-scale application re-factoring, client communication to get an understanding of the requirement, software architecture, writing unit test cases using PHPUnit, Cypress.

  In the short run, my objective is to build solid experience in cloud/software architect, cloud infrastructure, software development.

  I'm looking for an enthusiastic team to work for that will provide me with challenging work that I can learn from and contribute to. I'd like to work on:
  - Build and maintain application infrastructure and technical solutions on AWS, Azure, and GCP.
  - Want to introduce or improve DevOps practices in application development or in CloudOps.
  - and Consult businesses with their Digital Transformation with Containers and Kubernetes, Monitoring and Observability and Cloud Strategy and Assessment – Adoption & Transformation, Assessment and Optimization, and Application Performance.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Visionet Systems Inc.
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: DevOps/Senior Consultant Cloud Services
        caption: Oct 2018 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: |
          - Implemented Observability Framework for Regeneron Pharmaceuticals Inc. as DevOps Consultant.
          - Prepared multi env Kubernetes cluster using ansible and microservices architect for Dubai Municipality on-site for Mendix platform as DevOps Consultant.
          - Prepared multi env Kubernetes cluster using ansible for microservices architecture for Nodejs as DevOps Consultant.

      - layout: left
        title: Nextbridge Ltd.
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Software Engineer
        caption: Oct 2014 - Oct 2018 - 4 yr 1 mos
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: |
          - Member of Vteams Star, MEAN and Laravel Trainer, Interviewer, Vteams Research, and Code Reviewer.
          - Managed various project milestones through the entirety of the SDLC process, Maintain project development roadmap, Prepare application requirement by communication with clients, Provide the solution to resolve various requirements.
          - Prepared and deployed infrastructure and CI/CD solution on AWS to maintain Laravel SAAS based CRM with separate database multi-tenancy.
          - Prepared and deployed CI/CD solution for angular, node js, and MongoDB based learning management system on GitLab to deploy on a dedicated host. 
          - Prepared and deployed solution of nightly build server for angular and node js base unit testing on AWS.
          - Prepared and deployed infrastructure and CI/CD solution for angular based CRM application on AWS with DeployBot.
          - Worked on angular based CRM (Customer Relation Management) based on different applications.  
          - Worked on QA Automation to develop the test cases using Cypress for angular2+ based application.
          - Developed CRM SASS application based on Laravel with separate database multi-tenancy.
          - Developed the mobile API for the CRM SASS application.
          - Managed the AWS services which include EC2, S3, RDS, SES, SQS.

      - layout: left
        title: Maavra Technologies
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: PHP Developer
        caption: Jun 2014 - Oct 2014 - 5 mos
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Key Responsibilities:
          - Taking part in a squad-oriented environment to develop and Maintain complex web-based applications.
          - Managing existing code base, to include troubleshooting bugs and adding new characteristics

      - layout: left
        title: GreenTech International Ltd
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Web Application Developer
        caption: Jan 2013 - May 2014 - 1 yr 5 mos
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Key Responsibilities:
          - Managing and developing various Database-driven Websites, Content Management Systems.
          - Application development using various Web Frameworks (Codeigniter, Zend)
          - Updating the site with new features, fix application issues and code irregularities.
          - Preparing manuals of Task Processes, Analyzing, and improvising the procedures used for different tasks.

      - layout: left
        title: E-till Solution
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: PHP Application Developer
        caption: Sep 2012 - Dec 2012 - 4 mos
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Key Responsibilities:
          - Managing and developing various Database-driven Websites, Content Management Systems.
          - Application development using OOAD, Object Oriented Programming (OOP), and Relational Database Management Systems (RDBMS).
          - Updating the site with new features, fix application issues and code irregularities.
          - Convey project requirements, risks as well as assumptions to project team along with client.
          - Implementing & Analyzing different SEO tasks as per the defined QA processes and standards.
          - Preparing manuals of Task Processes, analyzing and improvising the procedures used for different tasks.

      - layout: left
        title: Xpert Solution
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: PHP/MySQL Web Application Developer
        caption: May 2011 - Sep 2012 - 1yr 5 mos
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Key Responsibilities:
          - Perform on multiple projects all together in fast-paced deadline-driven atmospheres.
          - Building and maintenance of core PHP based web applications according to client requirement with reusable code preferably using classes and libraries.
          - Convey project requirements, risks as well as assumptions to project team along with client.
          - Testing and debugging new programs. Preliminary testing the site to make sure that it is functioning properly.
          - Preliminary testing the site to make sure that it is functioning properly.
          - Updating the site with new features, fix application issues and code irregularities.
          - Writing queries and contributing to database design and developments using MySQL.
  - title: Projects
    layout: list
    content:
      - layout: center
        title: Wolters Kluwer
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Consultant Cloud Engineer
        # caption: Oct 2018 - Present
        quote: >
          AWS, Azure, CaaS, Kubernetes, Helm, Docker, Observability using Prometheus, Prometheus Alert 
          Manager, Grafana, Custom Exporters, Terraform, Ansible, Python, Azure Devops, AKS, EKS.
        description: |
          Worked on CaaS (Container as Service), which is an automated platform to deploy kubernetes clusters on AWS and Azure cloud 
          providers. Along with the cluster few additional security, logging and monitoring components are deployed in each of the
          clusters. Wrote ansible playbook to automate custom terraform and Helm commands to deploy infrastructure using terraform and components charts using Helm3.
      - layout: center
        title: Cloud Management Platform
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Technical Architect
        # caption: Oct 2018 - Present
        quote: >
          AWS, Azure, ManageIQ, NodeRed, Kubernetes, Helm, Docker, Observability using Prometheus, Prometheus Alert Manager, Grafana, Custom Exporters, Terraform.
        description: |
          Worked as a Technical Architect, where my responsibility was to manage and guide the team of Cloud engineers. Prepared various cloud platform solutions for AWS and Azure and automate the process of infra deployment through Terraform, NodeRed and ManageIQ.
      - layout: center
        title: My Telenor – Telenor Pakistan
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: DevOps Consultant
        # caption: Oct 2018 - Present
        quote: >
          Kubernetes, Helm, Docker, Prometheus, Prometheus Alert Manager, Grafana, Custom Exporters, Git, TFS, Azure DevOps, Android and IOS auto-build, S3.
        description: |
          Prepared the multiple environments Kubernetes cluster using kubeadm. Being a part of the talented team as a DevOps Consultant worked alongside software, security engineers, and Solution architect to build a reliable platform. Prepared the observability implementation plan that includes monitoring infrastructure setup and resource onboarding. Prepared/Performed chaos engineering and platform load testing on the Production Kubernetes cluster. Prepared the power shell and shell scripting for various purposes and custom Prometheus exporters using python and NodeJS.
      - layout: center
        title: Observability Framework – Regeneron Pharmaceuticals Inc.
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: DevOps Consultant
        # caption: Oct 2018 - Present
        quote: >
          Kubernetes, Helm, Docker, Prometheus, Prometheus Alert Manager, Grafana, Exporters, Git, Bitbucket, Jenkins, EKS, ECR, EC2, Terraform, S3, DynamoDB, RDS, and CloudWatch.
        description: |
          Prepared the multiple environments Kubernetes cluster using Terraform on EKS for the various accounts. Being a part of the talented team as a DevOps Consultant worked alongside software, security engineers, and Solution architect to build a reliable platform. Prepared the observability implementation plan that includes monitoring infrastructure setup and resource onboarding. Prepared/Performed chaos engineering and platform load testing on EKS Kubernetes cluster for production/staging environment. Prepared the power shell and shell scripting for various purposes and custom Prometheus exporters using python and go-lang.
      - layout: center
        title: Rapid Application Development – Dubai Municipality - Onsite
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: DevOps Consultant / Cloud Engineer
        # caption: Oct 2018 - Present
        quote: >
          Kubernetes, Helm, Ansible, Docker, Private Docker Registry, Oracle DB, F5, Mendix, Git/SVN, Gitlab, Chaos engineering, SVN.
        description: |
          Prepared the multiple environments of Kubernetes cluster using Ansible for micro-services Mendix platform on on-premises infrastructure. Being a part of the talented team as DevOps Consultant worked alongside software, security engineers, and Solution architect to build a reliable platform. Prepared the CI/CD on Gitlab for multiple Mendix based applications, and prepared the automated scripts to get the source from SVN to GIT. Prepared/Performed chaos engineering and platform load testing on on-premises Kubernetes cluster for production/staging environment.
      - layout: center
        title: OTT - Telenor
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: DevOps Architect
        # caption: Oct 2018 - Present
        quote: >
          Kubernetes, Helm, Ansible, Docker, Private Docker Registry, Postgres9, Azure DevOps, MINIO Storage, NGINX based reverse proxy, ModSecurity, and SSL letsencrypt certificate, NodeJS, Javascript.
        description: |
          Worked on a micro-services architect for bare metal setup on PTCL Cloud using Ansible as DevOps Architect. Being a part of a talented team that works alongside software engineers and security engineers to build a reliable and highly scalable infrastructure.

      - layout: center
        title: UNFI Easy Options - UNFI
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Technical Lead
        # caption: Oct 2018 - Present
        quote: >
          Magento Cloud, AWS EC2, S3, CodePipeline, CodeCommit, CodeBuild, Github, RDS, ECR, EKS, Docker, Magento2.
        description: |
          Worked as Technical Lead for Magento2 Cloud-based applications. Participated in the design, development, and implementation of complex features/requirements. Managed Magento2 cloud, AWS services, and Magento2 based application releases. Provide expertise on infrastructure solutions, strategic direction, and system architecture. Prepare and manage application technical requirements from application functional. Prepared the infrastructure for GitOps with CodeCommit and Magento2 Cloud.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
